[build]
  command = "npm run build"
  functions = "functions"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
