[build]
  command = "npm run build"
  publish = "public"
  functions = "functions"

[dev]
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/dashboard/*"
  to = "/dashboard"
  status = 200

